### PR TITLE
Add messaging library

### PR DESCRIPTION
**Pull request by jonapap**
Define a crate for messaging. Using a separate crate will allow the ground-station to easily use it. Also, using `Postcard` to serialize and deserialize the data.

For now, I've created placeholder message definitions. Eventually, we'll define the proper messages to send across.

Ideas which could maybe go in another PR:
- Regression tests for the messages. Make sure the size doesn't exceed 64 bytes and make sure we don't break compatibility with older messages when we make changes here.
- Figure out what we do for logging (I already have ideas for this, working on it)

### CODE REVIEW

**Review by NoahSprenger — APPROVED** [review]
Postcard is a good choice. I have no complaints everything looks good.

**Review by Text-Input — COMMENTED** [review]
Review looks good, but I am curious about why you created a new communication board. I thought this would have gone in the main board, no?

**Comment by jonapap** [comment]
I knew Noah was working on his stuff, so I didn't want to modify too much the main board. After this round of PRs, I'll merge those two boards together, move to RTIC, and figure out which logic stays in the board crates and which will be moved to other files/crates.

**Comment by jonapap** [comment]
@Text-Input here, with Noah's stuff merged in and the testing PR opened, I've removed the communication board

**Review by NoahSprenger — APPROVED** [review]
Looks good!

**Pull request merged**
